version: '2'

services:
  postgresql-e2e-master:
    image: docker.io/bitnami/postgresql:14
    ports:
      - '5434:5432'
    environment:
      - POSTGRESQL_REPLICATION_MODE=master
      - POSTGRESQL_REPLICATION_USER=repl_user
      - POSTGRESQL_REPLICATION_PASSWORD=repl_password
      - POSTGRESQL_USERNAME=vulndb
      - POSTGRESQL_PASSWORD=vulndb
      - POSTGRESQL_DATABASE=vulndbtest
      - ALLOW_EMPTY_PASSWORD=yes
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U vulndb'"]
      interval: 5s
      timeout: 10s
      retries: 6

  postgresql-e2e-slave:
    image: docker.io/bitnami/postgresql:14
    ports:
      - '5435:5432'
    depends_on:
      postgresql-e2e-master:
        condition: service_healthy
    environment:
      - POSTGRESQL_REPLICATION_MODE=slave
      - POSTGRESQL_REPLICATION_USER=repl_user
      - POSTGRESQL_REPLICATION_PASSWORD=repl_password
      - POSTGRESQL_MASTER_HOST=postgresql-e2e-master
      - POSTGRESQL_MASTER_PORT_NUMBER=5432
      - ALLOW_EMPTY_PASSWORD=yes
      - POSTGRESQL_PASSWORD=vulndb

  e2e:
    image: postman/newman
    command: ["run",
      "/postman/Vulnerability_DB_API.postman_collection.json",
      "--environment=/postman/VulnerabilityDBAPI.postman_environment.e2e.json",
      "--bail",
      ]
    volumes:
      - "../_resources/e2e/postman:/postman"
    extra_hosts:
      - "host.docker.internal:host-gateway"
