language: go
go:
  - 1.17.2
services:
  - docker
env:
  global:
    - CGO_ENABLED=0
    - GO111MODULE=on
gobuild_args: -a -tags netgo -ldflags '-w'
go_import_path: github.com/adevinta/vulnerability-db-api
before_script:
  - _script/start-pg
script:
  - go install ./...
  - go test -short -v $(go list ./... | grep -v /vendor/)
  - source _script/setup-e2e-tests.sh
  - _script/run-e2e-tests.sh
after_success:
  - bash -c 'source <(curl -s https://raw.githubusercontent.com/adevinta/vulcan-cicd/master/docker.sh)'
