dist: focal
language: go
go:
  - 1.21.x
services:
  - docker
env:
  global:
    - CGO_ENABLED=0
gobuild_args: -a -tags netgo -ldflags '-w'
go_import_path: github.com/adevinta/vulnerability-db-api
script:
  - go install ./...
  - go test -short -v $(go list ./... | grep -v /vendor/)
  - _script/run-e2e.sh read
after_success:
  - bash -c 'source <(curl -s https://raw.githubusercontent.com/adevinta/vulcan-cicd/master/docker.sh)'
