[api]
max_size = 100
default_size = 20

[postgresql]
host = "$PG_HOST"
port = "$PG_PORT"
user = "$PG_USER"
pass = "$PG_PASSWORD"
db = "$PG_NAME"
sslmode = "$PG_SSLMODE"

# Read replica DB. If specified the endpoints that only read data from the DB
# will use this db instance instead of the RW one set above.
[postgresql_read]
host = "$PG_HOST_READ"
port = "$PG_PORT_READ"
user = "$PG_USER_READ"
pass = "$PG_PASSWORD_READ"
db = "$PG_NAME_READ"
sslmode = "$PG_SSLMODE_READ"

[log]
level = "$LOG_LEVEL"
