[api]
max_size = 100
default_size = 20
port = 8080

[postgresql]
host = "$PG_HOST"
port = "$PG_PORT"
user = "$PG_USER"
pass = "$PG_PASSWORD"
db = "$PG_NAME"
sslmode = "$PG_SSLMODE"

[log]
level = "$LOG_LEVEL"
