[api]
max_size = 100
default_size = 20

[postgresql]
host = "localhost"
port = "5434"
user = "vulndb"
pass = "vulndb"
db = "vulndbtest"
sslmode = "disable"

[postgresql_read]
host = "localhost"
port = "5435"
user = "vulndb"
pass = "vulndb"
db = "vulndbtest"
sslmode = "disable"

[log]
level = "INFO"
